Add sentry for backups

diff --git a/ansible/roles/database/templates/remote-backup.sh.j2 b/ansible/roles/database/templates/remote-backup.sh.j2
--- a/ansible/roles/database/templates/remote-backup.sh.j2
+++ b/ansible/roles/database/templates/remote-backup.sh.j2
@@ -1,2 +1,16 @@
 #!/bin/bash
+export SENTRY_DSN='{{ sentry_backup_dsn }}'
+
 /usr/local/bin/rclone --config="/root/.config/rclone/rclone.conf" --log-file /var/log/rclone.log copy -L /var/lib/pgbackrest DigiStorage:/pgbackrest/{{ inventory_hostname }}
+
+# Capture the exit code
+EXIT_CODE=$?
+
+# Check if rclone executed successfully
+if [ $EXIT_CODE -eq 0 ]; then
+    echo "rclone execution was successful."
+    sentry-cli send-event -m "{{ inventory_hostname }} pgbackrest OK"
+else
+    echo "rclone execution failed with exit code $EXIT_CODE."
+    sentry-cli send-event -m "{{ inventory_hostname }} pgbackrest failed: $EXIT_CODE" --logfile /var/log/rclone.log
+fi
